---
- name: Install Java
  dnf:
    name: java-11-openjdk
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Jenkins repository
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: Jenkins repository
    baseurl: https://pkg.jenkins.io/redhat-stable/
    gpgcheck: yes

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Get Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Store Jenkins password in SSM
  aws_ssm_parameter:
    name: "/{{ project }}/{{ env }}/jenkins/initial-password"
    value: "{{ jenkins_password.stdout }}"
    type: "SecureString"
    region: "{{ aws_region }}"
  delegate_to: localhost
  become: no