resource "aws_ssm_parameter" "jenkins_admin_password" {
  name        = "/${var.project}/${var.env}/jenkins/admin-password"
  description = "Jenkins admin password"
  type        = "SecureString"
  value       = "ChangeMe123!" # You'll update this via Ansible Vault

  tags = {
    Name    = "${var.project}-${var.env}-jenkins-admin-password"
    Project = var.project
    Env     = var.env
  }
}

resource "aws_ssm_parameter" "jenkins_api_token" {
  name        = "/${var.project}/${var.env}/jenkins/api-token"
  description = "Jenkins API token"
  type        = "SecureString"
  value       = "dummy-token" # Will be generated by Jenkins

  tags = {
    Name    = "${var.project}-${var.env}-jenkins-api-token"
    Project = var.project
    Env     = var.env
  }
}