all:
  children:
    bastion:
      hosts:
        bastion:
          ansible_host: "{{ lookup('env', 'BASTION_IP') }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/cloud-devops-lab-2025-key.pem
    app:
      hosts:
        app:
          ansible_host: "{{ lookup('env', 'APP_PRIVATE_IP') }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/cloud-devops-lab-2025-key.pem
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@{{ hostvars[\'bastion\'][\'ansible_host\'] }}"'