---
- name: Configure all servers
  hosts: all
  become: yes
  roles:
    - common
    - security

- name: Configure bastion server
  hosts: bastion
  become: yes
  roles:
    - docker

- name: Configure app server
  hosts: app
  become: yes
  roles:
    - docker
    - jenkins