---
- name: Install Docker
  dnf:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add devops user to docker group
  user:
    name: devops
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'